### ISSUE TITLE
Request to merge Updated Django_blog.

### ISSUE THREAD

**Issue by tester-zero** [TheAbhijeet/Django_blog#34]
hi Abhijeet,

 I have made some changes in the Django_blog project, please check them. in pull requests section,

 I'm eager to see this contribution become a part of the project.

 If there are any remaining concerns or if there's anything specific you'd like me to do, please let me know, and I'll be more than happy to assist.

**Comment by TheAbhijeet** [comment]
Hi @AlphaDarkmoon 

Thanks for the PR, but I can't really change much in this repo because then my article becomes outdated [https://djangocentral.com/building-a-blog-application-with-django/](url)

This repo serves as a reference point for those who are learning from the article. 

But don't worry I have a better blog implementation that I will open source later this year, I hope I see you there :)
